version: '3.8'

services:
  backend:
    build:
      context: ./url-shortner
    ports:
      - "8080:8080"  # Expose Go backend on port 8080
    depends_on:
      - redis
    networks:
      - app-network

  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"  # Expose Next.js frontend on port 3000
    depends_on:
      - backend  # Ensure the backend starts first
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"  # Expose Redis on port 6379
    networks:
      - app-network
    volumes:
      - redis-data:/data  # Persist Redis data  

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
    driver: local
